name: CD (dev)

on:
  push:
    branches: ["develop"]

permissions:
  contents: read
  packages: write

env:
  REPO_LOWER: ${{ github.repository | toLower }}

jobs:
  build-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Docker login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (tag dev)
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE=ghcr.io/${REPO_LOWER}/appdevops
          docker build -t $IMAGE:$SHORT_SHA -t $IMAGE:latest-dev app
          docker push $IMAGE:$SHORT_SHA
          docker push $IMAGE:latest-dev